### ISSUE TITLE
Doesnt work on Laravel 7.x

### ISSUE THREAD

**Issue by thatobabusi** [barryvdh/laravel-debugbar#1030]
In .env I have
APP_ENV=local
APP_DEBUG=true

Laravel Framework 7.6.2
PHP 7.4.1

When I ran the ```composer require barryvdh/laravel-debugbar --dev``` it installed normally without an errors.

When it was finished I check the vendor/barryvdh folder and the package is not there....

Am I doing something wrong or it's just not compatible anymore?

**Comment by SupianIDz** [comment]
Are you sure you installed it in your project folder ?

**Comment by thatobabusi** [comment]
It appears as if it does not install at all. Regardless of what I try. Would be nice if there was an error during the installation process...

Only other thing I got was 
```Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.```

So I ran composer update --lock, still no joy.

**Comment by leMaur** [comment]
Hi @thatobabusi, I had the same problem. 
My configuration is: Laravel 7.9.2, Php 7.4.5.

After different tests, I've found that the problem was the enabling of _explain_ in the debugbar's config file. In my case I'd put `options.db.explain.enabled = true` with a **sqlite** database.

I don't know if it's your case too.

@barryvdh it's a desired behavior to totally hide the debug-bar when using the **sqlite** database and enabling the `options.db.explain.enabled = true` option in the config file?
If not, do you want I open an issue about that and how to reproduce it?

**Comment by AlexMalikov94** [comment]
So to install a new package, you need to either ```composer require vendor / package``` or manually add it to ```composer.json``` and then ```composer update vendor / package```. And so ```composer``` just reads the dependencies from the composer.lock file

**Comment by blakethepatton** [comment]
It installed just fine for me, just doesn't seem to show up.

**Comment by mikewink** [comment]
I had the same problem as described above. The reason is that the EXPLAIN in SQLite works differently and comes in two flavors.

I created a pull request to get basic `EXPLAIN` support for SQLite working. If the maintainer approves, I will add support for `EXPLAIN QUERY PLAN` as well.

PR: https://github.com/barryvdh/laravel-debugbar/pull/1315

I think SQLite is a very capable piece of software and Debugbar support can be improved. :)
