### ISSUE TITLE
Debugbar in Laravel 8 not working

### ISSUE THREAD

**Issue by fscaptain** [barryvdh/laravel-debugbar#1109]
Access to resources 
`GEThttp://l8test.local/_debugbar/assets/stylesheets?v=1599507159&theme=auto`
returning `"404 not found"` .
Routes are present and the Debugbar is enabled via` 'enabled' => true,` in the debugbar.php inside the config folder.

Laravel: 8.6.0
DebugBar: 3.5.1
PHP: 7.4.10

**Comment by w-lopes** [comment]
Same problem here :/ 
I disabled it to keep coding at localhost.

**Comment by nasrulhazim** [comment]
> Access to resources
> `GEThttp://l8test.local/_debugbar/assets/stylesheets?v=1599507159&theme=auto`
> returning `"404 not found"` .
> Routes are present and the Debugbar is enabled via` 'enabled' => true,` in the debugbar.php inside the config folder.
> 
> Laravel: 8.6.0
> DebugBar: 3.5.1
> PHP: 7.4.10

How you did the installation? mine works fine on Laravel 8.8.0, PHP 7.4.10 and DebugBar 3.5.1

**Comment by rossjcooper** [comment]
Try updating to ^3.5.0 as Laravel 8 support was added then https://github.com/barryvdh/laravel-debugbar/releases/tag/v3.5.0

**Comment by mbogit** [comment]
Same here

```
Illuminate\Contracts\Container\BindingResolutionException
Target class [Barryvdh\Debugbar\Controllers\AssetController] does not exist.
http://site.test/_debugbar/assets/javascript?v=1599507159
```

This route `_debugbar/open` though can find its controller

**Comment by nasrulhazim** [comment]
probably you can try `rm boostrap/cache/*.php` and `php artisan config:clear`.

or worst case, remove all packages with `rm -fr vendor/` and `composer install`.

**Comment by OPM87** [comment]
For me it crashes at LaravelDebugbar.php::898 ... the route does not exist.

Seems this [commit ](https://github.com/barryvdh/laravel-debugbar/commit/28149253410010e5a0d6c08871f8096eb8ac0490#diff-0dcb363b46434ce2fc8f2969d3e4a183bab1157c17425fb826da41427cff01e6) brokes the routing.
The routes will now defined in the register() method of the ServiceProvider instead of the boot() method.
According to [laravel docs](https://laravel.com/docs/8.x/providers#writing-service-providers) this is not allowed.

Switching the "$this->loadRoutesFrom(realpath(__DIR__ . '/debugbar-routes.php'));" back to the boot() method works.

**Comment by echobash** [comment]
> Try updating to ^3.5.0 as Laravel 8 support was added then https://github.com/barryvdh/laravel-debugbar/releases/tag/v3.5.0

You are amazing. thank you.
