### ISSUE TITLE
Debugbar dark theme text not visible

### ISSUE THREAD

**Issue by Naadi** [barryvdh/laravel-debugbar#1123]
![image](https://user-images.githubusercontent.com/45055960/96579889-1c899c00-12f5-11eb-9784-fc567df69117.png)
Text is not visible in few tabs in debugbar. 
i can only see the text if i select them

**Comment by ChrisThompsonTLDR** [comment]
This is still an issue.

**Comment by pafernandez-oesia** [comment]
I was having the same issue. It seems that **ListWidget** styles are easily overriden with any other style that applies to lists in your CSS code. Keep in mind that **Debugbar** is rendered inside your app, so any other loaded CSS styles are applied.

In my case, I had a CSS rule in the app thas was causing the text to display in a dark color:
```
.white-content ul li {
    color: #1d253b;
}
```

As you can see, it doesn't have any direct relation to **Debugbar**, but it applies because it is more specific than **Debugbar** list styles.

It can be solved adding another rule for **Debugbar ListWidget** styles that resets the color:
```
div.phpdebugbar ul.phpdebugbar-widgets-list li.phpdebugbar-widgets-list-item {
    color: #EDF2F7;
}
```

Anyway, this selector can be added in a rule found in the `laravel-debugbar-dark-mode.css` file. I've created a PR with the proposed solution (https://github.com/barryvdh/laravel-debugbar/pull/1334).
