### ISSUE TITLE
PHP 8 support?

### ISSUE THREAD

**Issue by vladislavtkachenko** [barryvdh/laravel-debugbar#1133]
Hello, do you have any plans to support php 8?

Thank you for your work

**Comment by minayaleon** [comment]
I'm working with PHP8, so far it's works

**Comment by vladislavtkachenko** [comment]
![image](https://user-images.githubusercontent.com/21283123/101175051-bd3ddc00-3655-11eb-9f8b-480900359bc5.png)

**Comment by minayaleon** [comment]
It's correct, i was able to replicate thats error. but you can use PHP 7.4 only for that case:
1. Add package to composer (dev)
2. Use docker with PHP 7.4 -> docker run --rm -it -v $(pwd):/var/www codepso/php:7.4-fpm-mysql composer install  
3. codepso/php:7.4 its a php 7.4 image, you can use another

**Comment by vladislavtkachenko** [comment]
why do I need to install php 7.4 if the question is support and the ability to install the package using php 8 ?

**Comment by vladislavtkachenko** [comment]
@barryvdh what do you think about ?

**Comment by kblais** [comment]
The issue is not laravel-debugbar, but it's dependency (https://github.com/maximebf/php-debugbar). If you take a look at the [composer.json](https://github.com/barryvdh/laravel-debugbar/blob/9bddf89abaec063bb4d1753ba87e1b1d5620e729/composer.json#L13), you'll see this package is already ready for PHP 8.

And concerning maximebf/debugbar, it seems like they are already working on PHP 8 compatibility, as the last commits concern tests with PHP 8

**Comment by barryvdh** [comment]
Running the tests for PHP8 as we speak, will tag when passing; https://github.com/maximebf/php-debugbar/pull/461

**Comment by vladislavtkachenko** [comment]
@barryvdh thank you for merging! Thank you for you work!

**Comment by barryvdh** [comment]
It's tagged now as 1.16.4, so should be available in a few minutes or so.

**Comment by vladislavtkachenko** [comment]
all is ok now
![image](https://user-images.githubusercontent.com/21283123/101342374-8523dc80-3893-11eb-9605-77a29c0887a7.png)
