### ISSUE TITLE
Didn't show quey when use View:share() ?

### ISSUE THREAD

**Issue by tommy66374** [barryvdh/laravel-debugbar#1228]
https://laravel.com/docs/8.x/views#sharing-data-with-all-views

Hello guys, when i use this, laravel-debugbar didn't show the query

```
    public function boot()
    {
        View::share('users', User::all());
    }
```

**Comment by iamine** [comment]
i'm facing the same issue, when i use User::all in boot, the query not shown in Queries

**Comment by wallaaa** [comment]
I am having this same issue with Laravel 9, I have a query running in the boot method of the service provider that I load into my view using View::share.

The debugbar does not reference this query anywhere.

I tried to reorder the service providers so that the debugbar is above where I load this service provider that has the query. I am not sure if this matters but it didn't have any effect anyways when I put the debugbar above it.

config/app.php 

'providers' => [

//Debugbar
Barryvdh\Debugbar\ServiceProvider::class,
//Custom Service Providers
App\Providers\AdminLayoutServiceProvider::class,  <- this is the provider i have my query in
