### ISSUE TITLE
Problem with Vue 3

### ISSUE THREAD

**Issue by cstoehr** [barryvdh/laravel-debugbar#1298]
If you install the current version of vue (version 3) there is a mass on errors in the console and you can't navigate in the debugbar.

![image](https://user-images.githubusercontent.com/9281177/154848427-8c35f27a-923b-4d60-bad7-a58256e8564c.png)

**Comment by hopkins385** [comment]
I've installed Laravel 9 + Vue 3 + Debugbar and do not experience such issues. 
The reason might be maybe because your Vue3 mounted div contains the debugbar script tags. 
Ususally the setup is like <div id="app></div> <script>debugbar specific js here</script>
How does your app.blade.php look like?

**Comment by TasneemWahdan** [comment]
I faced the same problem after adding Vue to my project.
I was giving id="app" to the body tag. 
I solved the problem by adding a div inside the body and giving it id='app'.
