### ISSUE TITLE
Can I use barryvdh/laravel-debugbar in laravel 9 / Inertiajs/vuejs 3  app?

### ISSUE THREAD

**Issue by sergeynilov** [barryvdh/laravel-debugbar#1310]
Is it possible to install and use barryvdh/laravel-debugbar in laravel 9 / Inertiajs/vuejs 3  app?

I installed it and added line in .env :

`DEBUGBAR_ENABLED=true`

But do not have bar at bottom of the page...

Have I to make some more steps ?

Thanks!

**Comment by anibalealvarezs** [comment]
Yes. It works great with Laravel 9.

Make sure that the service provider is correctly added, and that you have recompiled the app.js after installing it.

**Comment by sergeynilov** [comment]
Please, detalize if it works with Inertiajs ? When app is created with command :  
`  laravel new AppName  --jet
`and next Inertiajs is selected ?

**Comment by anibalealvarezs** [comment]
Yes, it does. Here is a package that uses it along with Inertia: https://github.com/anibalealvarezs/projectbuilder-package

**Comment by WalrusSoup** [comment]
Random note that I hope someone finds: this package can unintentionally cause mayhem in the storage/debugbar folder (on windows at least) when using [larave-vite](https://github.com/innocenzi/laravel-vite) if you have a window open with your testing suite (cypress). 

When you run [cypress](https://github.com/laracasts/cypress) it will move around .env files, this ended up causing my main window to break. I went to sleep and woke up to a horrific number of JSON files in the `storage/debugbar` folder. This is probably caused by the vite ping feature which kept firing into a 404.

**Comment by Mobin-khorushi** [comment]
it seems its not working anymore with most updated laravel breeze starter-kit and most updated debugbar 
it's totally working well but inertia losing SPA ability and will do reload or refresh on each request!

**Comment by parallels999** [comment]
?? Did you try `CTRL` + `SHIFT` + `R`?
That works for me
