### ISSUE TITLE
Empty Bindings and Backtrace

### ISSUE THREAD

**Issue by rolland97** [barryvdh/laravel-debugbar#1684]
![image](https://github.com/user-attachments/assets/69f8e75f-7fb7-44c6-989b-ac3915f5d32f)

Environment:
- Windows 11
- php 8.2.23
- Laravel 10.48.22
- Filament 3.2.115

**Comment by rolland97** [comment]
Laravel Debugbar v3.14.2 functions correctly, but the latest version (v3.14.3) is not working as expected.

**Comment by parallels999** [comment]
CC: @tpetry

**Comment by Johnefsh** [comment]
Same here any help please.

**Comment by tpetry** [comment]
> Laravel Debugbar v3.14.2 functions correctly, but the latest version (v3.14.3) is not working as expected.

Thanks for finding the exact version that broke this.

@mccahan This seems to be because of your `values.values()` change. I don't understand why it should be a problem, but its the only change. Are there any other possible implementations that would fix the edge case you had by extending the `Array` prototype?

**Comment by Johnefsh** [comment]
For me noting changed I just upgraded to version v3.14.3, should I return to v3.14.2 for now?

**Comment by mccahan** [comment]
@tpetry Whoops, this does in fact seem to be mine. I've got a PR in #1686

**Comment by Johnefsh** [comment]
I have uninstalled the laravel-debugbar and install it and I cleared my config but still having the same exact problem.

**Comment by barryvdh** [comment]
Can you try with v3.14.4 ?

**Comment by Johnefsh** [comment]
> Can you try with v3.14.4 ?

@barryvdh Thanks, this solved the issue.
