### ISSUE TITLE
Debugbar not opening

### ISSUE THREAD

**Issue by kuroski** [barryvdh/laravel-debugbar#238]
After installing, the bar appears normally, and if I inspect the elements, the information is there, the bar is not expanding.

![01](https://cloud.githubusercontent.com/assets/1855125/5292096/1804f642-7b44-11e4-90be-8a510d7d7462.png)

**Comment by tomzx** [comment]
@kuroski Is this fixed on your end? Can we close this?

If not, I suggest you start off by stripping out all javascript in your page. The debugbar uses jquery which may conflict with whatever you have in your page. Furthermore, it occurs quite often that issues with the debugbar are in fact due to other js libraries in the page.

**Comment by kuroski** [comment]
Yes, recently I did an update and the problem did not occur anymore.
