### ISSUE TITLE
Not working on local app.php

### ISSUE THREAD

**Issue by ablunier** [barryvdh/laravel-debugbar#292]
When I put the service provider on the providers array of my local app.php config file Debugbar is not working. I'm using it on a laravel 4.2 project.

**Comment by danielsan2099** [comment]
hi @ablunier, i have the same problem, Do you could solve?

**Comment by ablunier** [comment]
No, til now I couldn't :(

**Comment by tomzx** [comment]
@ablunier, @danielsan2099 Are you guys still facing some issues? If so, can you be more specific as to what is not working?

**Comment by tattedweazel** [comment]
For what it's worth, I found our Laravel 4.2 project was having the same issue with version 1.8. 

I immediately ensured this ServiceProvider is called before our own Routing ServiceProviders, yet that still didn't work.

I found 2 solutions that did finally work:

*Note: These only address situations where your project is, itself, using some form of Route ServiceProviders and not simply just using routes.php

First, I copied the routes out of the Debugbar ServiceProvider and put them into our primary Routing ServiceProvider directly, in the register() method. That actually worked well, but felt a bit hack-ish.

Second, in the Debugbar ServiceProvider, I moved the route registrations (just the 3 primaries I was having an issue with) into the register() method, instead of the boot() method. That also worked with no other changes needed. Sadly, this is an unsustainable fix since I directly modified the /vendor/Barryvdh/ServiceProvider file (which would get reverted anytime it's updated).

The first option works, but the second seems better. At least from my experience, route registration in ServiceProviders generally occurs in register() instead of boot(), and in this case its that difference that causes the issue. I'd submit a PR suggesting such change, but I'm one of the few developers that doesn't assume that the way I do things is the way the world should work... so I figured I'd leave a comment and maybe at least give someone else a view at how I got it working.

For reference, the three routes I keep mentioning are:
$this->app['router']->get(
            '_debugbar/open',
            array(
                'uses' => 'Barryvdh\Debugbar\Controllers\OpenHandlerController@handle',
                'as' => 'debugbar.openhandler',
            )
        );

        $this->app['router']->get(
            '_debugbar/assets/stylesheets',
            array(
                'uses' => 'Barryvdh\Debugbar\Controllers\AssetController@css',
                'as' => 'debugbar.assets.css',
            )
        );

        $this->app['router']->get(
            '_debugbar/assets/javascript',
            array(
                'uses' => 'Barryvdh\Debugbar\Controllers\AssetController@js',
                'as' => 'debugbar.assets.js',
            )
        );
