### ISSUE TITLE
Don`t work in sub domains also

### ISSUE THREAD

**Issue by mtonev** [barryvdh/laravel-debugbar#293]
I use laravel 5 and debug bar work only on general domain, not on subdomain.

**Comment by tomzx** [comment]
I'm not sure subdomains should cause an issue. Do you use chrome? Could you take a look and see if any of the debugbar requests (`_debugbar/assets/javascript` or `_debugbar/assets/stylesheets`) are returning 404s?

**Comment by Nacoma** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/1852424/19939637/d9a8fdcc-a0f7-11e6-9d65-005c67e23eac.jpg)

![selection_002](https://cloud.githubusercontent.com/assets/1852424/19939660/ed5ed364-a0f7-11e6-8a59-adbeeb9639a8.jpg)
![selection_003](https://cloud.githubusercontent.com/assets/1852424/19939754/3be39146-a0f8-11e6-8eee-271174c8640a.jpg)

Debugbar is trying to load `/` (`location` in my case) instead of its own assets.

**Comment by eyeoftigers** [comment]
yes they return 404
