### ISSUE TITLE
$app['config']->get('debugbar.enabled') is returning null after the last update.

### ISSUE THREAD

**Issue by vsmoraes** [barryvdh/laravel-debugbar#299]
Hi there!

I have a extension to your wonderful plugin that shows me all the request some api requests. So I've created a service provider to enable this extension only when the debug is true and debugbar is enable, but after the last update it is no longer possible.

```php
$this->app['config']->get('debugbar.enabled')
```

The line above should return ```true``` or ```false```, but it's returning ```null``` even with the plugin up and running.

**Comment by barryvdh** [comment]
null values are transformed here, in boot(): https://github.com/barryvdh/laravel-debugbar/blob/7bdf8acf3b955f4fcf922e74abdfdec370369196/src/ServiceProvider.php#L92

Not sure how to best fix this, because of some timing issues. You could set the `debugbar.enabled` value to `env('APP_DEBUG')` directly perhaps.

**Comment by vsmoraes** [comment]
Well, I've switched all the bindings from the ```register``` to the ```boot``` method on my service provider and, as long it is loaded after the debugbar, it should be ok ;)
