### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by OzanKurt** [barryvdh/laravel-debugbar#307]
phpdebugbar.addTab("views", new PhpDebugBar.DebugBar.Tab({"icon":"leaf","title":"Views", "widget": new PhpDebugBar.Widgets.TemplatesWidget()}));

The implementation of scripts give this error...

**Comment by barryvdh** [comment]
Any 404 errors on your scripts?

**Comment by OzanKurt** [comment]
No. I only have some errors on the JavaScript setups of Debugbar.

**Comment by OzanKurt** [comment]
Check this url "http://cansinal.com/?debug" so you can see the error yourself.

**Comment by tomzx** [comment]
```js
phpdebugbar.addTab("views", new PhpDebugBar.DebugBar.Tab({"icon":"leaf","title":"Views", "widget": new PhpDebugBar.Widgets.TemplatesWidget()}));

in a chrome console
new PhpDebugBar.Widgets.TemplatesWidget()
VM5120:2 Uncaught TypeError: undefined is not a function
```

**Comment by mbazalik** [comment]
I am experiencing same problem. 

In case you are trying Debugbar to be visible only upon providing a query parameter (?debug in this example) you are doing it probaly by setting up the config.debug when query parameter is available

    $debug = \Input::get('debug');
    if ((!\Config::get('app.debug') && isset($debug))) {
          \Config::set('app.debug', true);
    }

The problem is that the Debugbar then tries to load compiled js and css file from url which does not contain the query parameter anymore

    /_debugbar/assets/javascript?TIMESTAMP
    /_debugbar/assets/stylesheets?TIMESTAMP

The problem is is caused by _ViewCollector_ which is extending the _TwigCollector_ and that is extending _AssetProvider_ which then injects some css and js into compiled js and css file.

    public function getAssets()
        {
            return array(
                'css' => 'widgets/templates/widget.css',
                'js' => 'widgets/templates/widget.js'
            );
        }

Since when javascript and stylesheet are colected the debug is not turned on, the ViewCollector is no injected and therefor their javascript are ignored as well.

The possible fix here would be to update the AssetController for js and css to turn debug mode allways on

Cheers

Marian

**Comment by mbazalik** [comment]
Hi guys, I have found another way around this. We are using nginx and by following configuration, you can pretty much create desired GET parameter for those _debugbar requests

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ ^/_debugbar.* {
            set $args $args&debug=1;
            try_files $uri /index.php$is_args$args;
        }

So in that case, you just need to check in laravel for GET debug argument and you are able to switch debugging on and off appropriately

Cheers

Marian

**Comment by OzanKurt** [comment]
Wont work! What are you gonna do with ajax requests?

**Comment by mbazalik** [comment]
@OzanKurt - can you please give me some example? We are not using it to track ajax requests yet
