### ISSUE TITLE
Class 'App\Http\Controllers\Debugbar' not found !

### ISSUE THREAD

**Issue by mnameghi** [barryvdh/laravel-debugbar#316]
Hi
I add this line in app.php
`'Debugbar'  => 'Barryvdh\Debugbar\Facade'`
but when I use `Debugbar::error('Error!');` in my controller this error occured:

*Class 'App\Http\Controllers\Debugbar' not found*
Also I update composer and Debugbar showed in my app.

**Comment by barryvdh** [comment]
`\Debugbar::error('Error!');`
https://laracasts.com/lessons/namespacing-primer

**Comment by tanteng** [comment]
use Barryvdh\Debugbar\Facade as Debugbar;

I solved it like this.

**Comment by joeljerushan** [comment]
you can add `use Debugbar;` on top of your controller

**Comment by lawsonjt** [comment]
`use Debugbar;`   did not work for me.  tanteng's solution did work.   Cheers.

**Comment by liangshuocj** [comment]
tks

**Comment by pixeliner** [comment]
I know this is old and all but can someone please explain me why for some people it works just by using `use Debugbar;` and others not? Are there configs needed? Is it maybe a php version? I have no clue. But it seems in more and more repositories you always seem to get a solution to a problem but never an answer to why :(

**Comment by VasilSlavchev** [comment]
> I know this is old and all but can someone please explain me why for some people it works just by using `use Debugbar;` and others not? Are there configs needed? Is it maybe a php version? I have no clue. But it seems in more and more repositories you always seem to get a solution to a problem but never an answer to why :(

Basically you need to include the files from folder that you want to use in your current file. In olden times from earlier version of php it was endeed mandatory to include all the files from different packages and libraries. Now you can just define the namespace (folder) from where you wanna use the file and its methods. There is a multiple ways of doing that, and the reason why sometimes it works with just `use Debugbar;` and sometimes it needs `use \Debugbar;` that extra slash before the class name is because of the scope in which we are trying to include the file. In other words the namespace. For example you can include (use) the file in BlogController, but it depends in which namespace is the actual controller. Is it directly in the controllers folder or it is in a sub folder. So if we are deep in subfolders and we are trying to use  `use Debugbar;` only, laravel will try to find the class somewhere close to where we are. But that actually will not work, because the file is in another physical place. So laravel will try to use this file from `App\Controllers\Blog\Debugbar;` which is obviously wrong. To make it work with adding this extra slash before the class name laravel will automatically search for the file in the APP folders, vendor folders and etc. So thats why  `use \Debugbar;` will probably work for most of the cases. The best practice is to use laravel autoload packages so its registering them by itself. Or just registering the full namespace as `use Barryvdh\Debugbar\Facade as Debugbar;`. :)
