### ISSUE TITLE
ReferenceError: PhpDebugBar is not defined

### ISSUE THREAD

**Issue by todstoychev** [barryvdh/laravel-debugbar#318]
![screenshot](https://cloud.githubusercontent.com/assets/4498971/6863517/b8d43766-d45b-11e4-9799-3a6538e4d9f9.png)
I think that there is some problem with the assets

**Comment by Riari** [comment]
I can confirm, I'm getting this too (but only in Laravel 5).

**Comment by todstoychev** [comment]
Exactly. It is not working on Laravel 5

**Comment by barryvdh** [comment]
And you are on the latest 2.x release? Try changing the service provider to the first in the array, clearing routes, config, cache and compiled files.

**Comment by ravaboard** [comment]
Moving as a first thing in the providers array helped for me.

**Comment by Riari** [comment]
That worked for me as well, thanks Barry!

**Comment by slampenny** [comment]
Thought I'd mention this.... I was getting this exact error while I was using Swagger (specially Swaggervel). In my access logs, it said "connection being reset by peer while reading response header from upstream". After some googling I found out that my ouput_buffering value in php.ini was set to 4096, and I guess the headers phpDebugBar was sending were too large, because when I increased that to 65535, everything worked correctly.

**Comment by todstoychev** [comment]
Hm, changing the debug bar service provider to be the first in the providers array, worked.

**Comment by ThiagoHSGoncalves** [comment]
Hi,

I have same problem.
Move to the top of array, don't work for me.

Any ideas?

* Laravel 5 / DebugBar 2.0

Thanks.

**Comment by ThiagoHSGoncalves** [comment]
Hello,

Disregard the previous message.
I adjusted the httpd.conf Apache (block <Directory>) and now works perfectly.

Thank you.
