### ISSUE TITLE
Does not work with Lumen

### ISSUE THREAD

**Issue by lagseeing** [barryvdh/laravel-debugbar#334]
Keeps searching for non existent config path.

**Comment by barryvdh** [comment]
Yeah I think Taylor said Lumen didn't really work with packages. I'll have to take a look to see if I can get it working..

**Comment by GrahamCampbell** [comment]
If you want to use debugbar, lumen is probably the wrong choice for you. Just go and use Laravel.

**Comment by frdmn** [comment]
:+1: for Lumen support

**Comment by micc83** [comment]
Because of its minimal structure Lumen is pretty good for teaching. In this scenario it would be very useful having laravel-debugbar support.

**Comment by edmarriner** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:-1: for lumen support. I strongly believe that if you need this, using Lumen is a bad idea. Just use Laravel.

**Comment by yadakhov** [comment]
+1 For looking for lumen support and google brought me here.

**Comment by meSingh** [comment]
:+1:  for lumen support..

**Comment by theskillz** [comment]
:+1:  for Lumen support

**Comment by Cosmeen** [comment]
:+1: for Lumen support

**Comment by GrahamCampbell** [comment]
This doesn't make sense for Lumen. If you need this for lumen you're going to end up making your app slower that if you'd used laravel.

**Comment by GrahamCampbell** [comment]
Lumen is designed in such a way that it loads as few services as it can. Debug bar would have to load a lot of these services. The way lumen actually disables these services actually adds more overhead so the total load time for using everything goes up.

**Comment by Cosmeen** [comment]
As from the Debugbar README file:
"_Note: Use the DebugBar only in development._"

For every new Laravel project I am working, while developing on local/staging machine, laravel-dubugbar is the first package I install.

**Comment by barryvdh** [comment]
I agree that performance wouldn't be a problem. I just don't have the time :(

**Comment by GrahamCampbell** [comment]
My point was not only performance, but I think it would be massive waste of time to work on.

**Comment by GrahamCampbell** [comment]
We already have laravel, and it works fine. Why spend hours on something else?

**Comment by barryvdh** [comment]
Well, Lumen is targeted for fast performance, so it would make sense to optimize your queries en debug your views etc, right?

**Comment by rgerovski** [comment]
In order to create high performance apps, we need appropriate tools (like this) to identify performance bottlenecks.
So, :+1: for Lumen support

**Comment by barryvdh** [comment]
Okay, initial support for Lumen is added in https://github.com/barryvdh/laravel-debugbar/commit/b9dc8f2626d0d1dc4792b3ab5b3eef0270abd092

Needed a few changes first, but now I've added a LumenServiceProvider and LumenDebugbar. I haven't checked the collectors yet, but I think many won't work properly because of the different events.

What works now is:
 - Queries
 - Messages ( `debugbar()->info($object)`)
 - Exceptions (when added manually)
 - Views
 - Request info
 - Files
 - Logs (with hardcoded logs/lumen.log path)
 - Mail (when illuminate/mail is required)
 - Auth (uses session)
 - Session (when enabled)
 - Events (just not as much)

What does not work/not tested
 - More detailed timing of booting etc.

**Comment by barryvdh** [comment]
I've added it to the readme. Merged the Debugbar class back together, just 2 seperate ServiceProviders. Closing this, let me know if there are any issues!
