### ISSUE TITLE
Track where database queries are coming from

### ISSUE THREAD

**Issue by rjosephporter** [barryvdh/laravel-debugbar#483]
Is there a way to track what class/file a database query was called? 

This will surely help a lot.

**Comment by barryvdh** [comment]
Did you try the db backtrace option in the config?

**Comment by rjosephporter** [comment]
Thanks! Exactly what I needed :+1:

**Comment by sebdesign** [comment]
May I raise a similar issue here?

I find the backtrace option very very useful, but I often need to backtrace a few more steps down the stack. E.g. I'm dealing with a legacy codebase, and I have several queries that are executed on my eloquent models (on relations or other methods).

That usually is a code smell that indicates that eager loading should be applied **before** calling those methods. But due to the *spagghetti* nature of that codebase, it's not easy to find the controllers or the intermediate classes which call those methods on the models. If I could backtrace a few levels back that would be very helpful.

Specifically, the `QueryCollector@findSource` could collect all the meaningful stack lines (instead of returning one the first one). The `debug_backtrace` method accepts a `$limit` parameter, which could be set in the config.

Then on the queries tab, the first backtrace result would be displayed (like it is currently). but when expading on a query, the stack trace could be listed along with the SQL and the bindings too.

**Comment by barryvdh** [comment]
Hmm could be interesting. Just a bit worried about the information overload..

**Comment by sebdesign** [comment]
I understand your concern, but as a designer (also) I could give it a try to make the information look neat.
Currently, the way the query information is displayed on expansion is a bit clunky. The params `<table>` is prepended to the left and is causing the hints to look weird.

**Comment by barryvdh** [comment]
Ok, I'm open for suggestions and improvements :)

**Comment by kirkbushell** [comment]
Was there any movement on this? 5 lines of stack trace is nothing when debugging queries :)
