### ISSUE TITLE
Show query count in table view

### ISSUE THREAD

**Issue by gabriel-vasile** [barryvdh/laravel-debugbar#545]
Hello, I've been using this debug bar for some time now, and it really helps a lot. 
However, what I'm missing the most is an easy option to show the query count for each request.

I think it would be great if this view would include a column for this purpose. Having to click on each request to be able to see the query count can get pretty tedious.

![query_count](https://cloud.githubusercontent.com/assets/10602896/18271972/cda39e7e-743d-11e6-932c-2584257606d6.png)

**Comment by VasileGabriel** [comment]
Since no one answered, most likely because to implement someting like this changes are necessary in this repo and also in php-debugbar I wrote some code for it.

[laravel-debugbar](https://github.com/VasileGabriel/laravel-debugbar/tree/append_meta)

[php-debugbar](https://github.com/VasileGabriel/php-debugbar/tree/append_meta)

If you guys think it is worth it adding this to the debugbar I will make a PR.
