### ISSUE TITLE
Debugbar exception: A non well formed numeric value encountered 

### ISSUE THREAD

**Issue by dodyagung** [barryvdh/laravel-debugbar#586]
Don't know what happens. The same project, in Windows XAMPP it's ok but in my Mac with laravel Valet it don't show anything. The error log said "local.ERROR: Debugbar exception: A non well formed numeric value encountered". I'm on Laravel 5.2

**Comment by barryvdh** [comment]
Which php version?

**Comment by dodyagung** [comment]
PHP 7. I think because it is on Nginx (Valet 2). I tried to use XAMPP for Mac that use Apache and it works.

**Comment by rommelandrea** [comment]
I've the same error but i run the application with `php artisan serve` 
My spec:
- php 7.1
- laravel/framework v5.1.31
- barryvdh/laravel-debugbar v2.2.3

**Comment by dexbarrett** [comment]
Same error here when upgraded my version of Laravel Homestead

PHP version 7.1
DebugBar version  2.2.2
Laravel version 5.1.35

**Comment by dexbarrett** [comment]
I solved this by updating my composer dependencies with `composer update`. 

This issue had to do with the [symfony/var-dumper](https://github.com/symfony/var-dumper) library. This issue was already reported (https://github.com/symfony/symfony/pull/19379) and fixed (https://github.com/symfony/var-dumper/blob/v2.7.16/Cloner/VarCloner.php#L318) since var-dumper **2.7.16**. I have `composer.lock` under version control so it would always pull versions from that file, and it's been a while since I updated my project's dependencies, so I had an old version of debugbar, which in turn had an older version of var-dumper (2.7.13).

Hopefully it will be the solution for others as well.

**Comment by Cysioland** [comment]
@dexbarrett Was a solution for me

**Comment by phpSpartacus** [comment]
@dexbarrett  thank you, composer update did the job

**Comment by ShuaiyiWu** [comment]
@dexbarrett thank you a lot, it worked for me

**Comment by vj-rana** [comment]
Great, it fixed for me too

**Comment by nizardani** [comment]
![tanya](https://user-images.githubusercontent.com/16665632/71980954-e2fb0f00-3253-11ea-807a-6d3cb7408ef2.png)

help me resolve my problem. I mauganmembuat features excor excel, but I saphalang Tompe date data on, and keturan suyesuaisuai data exce in mysql I am having this erorr (a non well formed numeric value encountered)
