### ISSUE TITLE
Can't install, Require PHP 7

### ISSUE THREAD

**Issue by ghost** [barryvdh/laravel-debugbar#686]
I got this error now when I try to install debugbar on my project

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
    - Installation request for doctrine/inflector == 1.2.0.0 -> satisfiable by doctrine/inflector[v1.2.0].


Installation failed, reverting ./composer.json to its original content.

```

**Comment by barryvdh** [comment]
Not sure why you post this here?

**Comment by zaenulhilmi** [comment]
Actually it's the first time I used lumen and want to use debugbar. When I try to install debugbar via composer. I got this error. 
I browse to doctrine/inflector on packagist, it said that version 1.2 is out at 2017-07-22, its not long ago. So maybe, I thought that this is not intentional to make debugbar require php 7. 
I'm asking appologize if I'm wrong. Seriously, I'm in doubt myself.

**Comment by zaenulhilmi** [comment]
The reason is illuminate/support require doctrine/inflector, and it need php 7. 

I ignore the requirement by using this. 
`composer install --ignore-platform-reqs`
and it work.

Thank you for your response and for your debugbar Barry.
