### ISSUE TITLE
DebugBar not display after login in Laravel 5.5-dev

### ISSUE THREAD

**Issue by dinhquochan** [barryvdh/laravel-debugbar#687]
Laravel version: 5.5
DebugBar version: 2.4

I `dd()` everywhere in core, i found it: `DebugBar\JavascriptRenderer` line: 872.
I `dd($this->debugBar->getData())` and:
- If i logout, i see `dd string`
- If i signed, i don't see that.
But when whoop (errors), bebugbar alway showing.

Below, just remove encrypt key to see whoop!
![screen shot 2017-08-06 at 23 19 18](https://user-images.githubusercontent.com/9979458/29005085-d4777af0-7afd-11e7-9a0a-4f550e4d6509.png)
When signed!
![screen shot 2017-08-06 at 23 19 27](https://user-images.githubusercontent.com/9979458/29005086-d47b6462-7afd-11e7-818c-7a3296ed1d15.png)
When logout
![screen shot 2017-08-07 at 23 56 27](https://user-images.githubusercontent.com/9979458/29037047-21ccd1b4-7bcc-11e7-8bd1-943f0caabca2.png)

**Comment by flaviomsb** [comment]
Hi @dinhquochan 

I got the same problem and figure out that debug bar was throwing an error like this:

`[2017-09-06 20:37:58] local.ERROR: Debugbar exception: Call to undefined method App\Models\User::getFullNameAttribute()`

My user model is in **App\Models** namespace just so you know, and I recommend you to dig into the Laravel logs in order to check for errors. As soon as I fixed my model for the missing method, the debug bar came back to work.

F

**Comment by dinhquochan** [comment]
Hi,

I fixed it 🎉 Just update to last version of Laravel and Debugbar.

**Comment by aik099** [comment]
Yes, you should use DebugBar 3.x with Laravel 5.5.x.

**Comment by spacedog4** [comment]
I'm having this same issue, if I'm logged with my custom provider it doesn't show up
