### ISSUE TITLE
L5.4 - Does the doco need to be updated to conditionally load the service provider?

### ISSUE THREAD

**Issue by ashgibson** [barryvdh/laravel-debugbar#708]
The installation section of the docs recommend installing as a dev only dependency as per below:

composer require barryvdh/laravel-debugbar --dev

but then add service provider to config/app.php and debug bar will only be shown when debug is on.

Won't this cause an issue on production where dev dependencies are not installed, therefore the service provider will fail to load?

**Comment by aik099** [comment]
You're correct. I guess the change was made to accompany Laravel 5.5+ service provider auto-discovery where you don't need to register service manually.

In any case the `--dev` switch must be removed, because:

1. provider should be added in all cases
2. the debug panel is only activated in debug mode, so no harm done

**Comment by barryvdh** [comment]
The change is made on the 5.5 version. You don't need to register it manually so no need for conditionals. Also, it is very recommended to use it for development only.

**Comment by aik099** [comment]
But what if you need to see something happening only on production servers and no way to replicate it locally?

**Comment by barryvdh** [comment]
Then you install it without - - dev, but I wouldn't recommend that, at least not by default. I made the change because in 5.5 the package loads by default when installed with composer, so could be unexpected for people who are using it conditionally.

**Comment by aik099** [comment]
I understand that of course. Since in Laravel 5.5 there is no way to avoid Laravel DebugBar service provider from being added automatically, then only way to hide it would be:

* either making it a dev dependency
* or disable it via config

If solution like I proposed in https://github.com/laravel/internals/issues/766 would be implemented, then having IP-based debug mode would allow to have debug bar always connected but enabled only for developers.

**Comment by aik099** [comment]
From README.md:

> If you don't use auto-discovery, add the ServiceProvider to the providers array in config/app.php

So it's possible to disable auto-discovery?

**Comment by barryvdh** [comment]
Yes
