### ISSUE TITLE
Debug::enable() not working

### ISSUE THREAD

**Issue by ben-shepherd** [barryvdh/laravel-debugbar#714]
Hi,

I am trying to use debugbar enable in production mode but only for my eyes.

I have added it to config/app.php and will work normally when I have it enabled via .env but I only want myself to be able to see it so I can find problems in production. 

I have tried the following code in Middleware and AppServiceProvider:
```
        Helper::pr([
            'AppServiceProvider',
            'enabled' => env('DEBUGBAR_ENABLED_FOR_USER_ONLY', false) ? 'yes' : 'no',
            'allowed ips' => env('DEBUGBAR_ENABLED_FOR_USER_IP', null)
        ]);

        if(env('DEBUGBAR_ENABLED_FOR_USER_ONLY', false)) {
            $ips = env('DEBUGBAR_ENABLED_FOR_USER_IP', null);

            if(strstr($ips,request()->ip())) {

                Helper::pr('Enabling...');

                \Debugbar::enable();
            }
        }
```

.env
```
DEBUGBAR_ENABLED=false
DEBUGBAR_ENABLED_FOR_USER_ONLY=true
DEBUGBAR_ENABLED_FOR_USER_IP=MY IP
```

Output on website:
```
Array
(
    [0] => AppServiceProvider
    [enabled] => yes
    [allowed ips] => MY IP
)
Enabling...
```

**Comment by aik099** [comment]
I've been working on #713, that would allow to dynamically enable/disable DebugBar from middlewares. Once merged it should be possible.

**Comment by ben-shepherd** [comment]
@aik099 is there an alternative I can use for now?

**Comment by aik099** [comment]
PR isn't merged and when it's merged you still need to wait for a release. Otherwise yes, you can use it.

**Comment by barryvdh** [comment]
It's merged, so you can install with `^3@dev`

**Comment by ben-shepherd** [comment]
@barryvdh sorry, stupid question but what exactly do I put it in my composer.json to get that to work?

**Comment by ben-shepherd** [comment]
@barryvdh  I think it might be because I'm on laravel 5.4

**Comment by ben-shepherd** [comment]
Ok, so I've upgraded to Laravel 5.5 now. I'm still having issues.

I've added this to the "web" array in middlewareGroups in Kernal.php

`debugbarMiddleware::class,`

The middleware code:

```
    public function handle($request, Closure $next)
    {
        Helper::pr([
            'middleware',
            'enabled' => env('DEBUGBAR_ENABLED_FOR_ADMINS', false) ? 'yes' : 'no',
            'is admin' => User::isUserAdmin() ? 'yes' : 'no',
        ]);

        if(env('DEBUGBAR_ENABLED_FOR_ADMINS', false) && User::isUserAdmin()) {

            Helper::pr(
                'Enabling debugbar...'
            );

            \Debugbar::enable();
        }

        return $next($request);
    }
```

The output on the website...
```
Array
(
    [0] => middleware
    [enabled] => yes
    [is admin] => yes
)
Enabling debugbar...
```

**Comment by lvbeck** [comment]
I have a similar problem, In production site, I set 'enabled' => false in the debugbar config file , because if you enable debugbar by default, the website performance is slow down for 10 times.

For instance with my site, the average page response time with debugbar disabled are less than 100ms, but it became to 1-2s after debugbar enabled.

However, I do want to enable debugbar on  run time only for admin users, so I create a debugbar middleware like this:

```
    public function handle($request, Closure $next)
    {
        if (Auth::guard('admin')->check()) {
            \Debugbar::enable();
        }
        return $next($request);
    }
```

and in $routeMiddleware array I register my middleware with a key:
```
'debugbar' => \App\Http\Middleware\DebugBarMiddleware::class, 
```
and in admin routes file I include the middleware:
```
Route::group(['middleware' => ['web', 'debugbar',
```

Unfortunately, above code does not work.

I found out \Debugbar::enable()  will not work if debugbar is disabled in config, which should be fix.

**Comment by Wotuu** [comment]
In case you, or others, are still having issues, I did the same as just just said above and it works now. When I log in as an admin the debug bar pops up, otherwise it stays hidden. I did need to set 'enabled' to 'true' in my settings though, I'll monitor the performance of my site and see if it's as as slow as you mention.

**Comment by shirazsoft** [comment]
@lvbeck 
This middelware  not work for me.
