### ISSUE TITLE
PHP Fatal error:  Cannot redeclare debug()

### ISSUE THREAD

**Issue by sinall** [barryvdh/laravel-debugbar#722]
> previously declared in vendor/barryvdh/laravel-debugbar/src/helpers.php:22

I suggest to use a class to wrap the helper functions, so there will be less naming conflicts.

**Comment by aarondfrancis** [comment]
I also had this issue, but with `measure`. 

I can't load my helpers file first because debugbar loads it's helpers via composer's autoloader.

Perhaps you could load your helpers _not_ using the composer.json files autoloader, which would allow me to 
1. not auto-discover debugbar
2. register my helpers
3. _then_ load debugbar
