### ISSUE TITLE
Non working on laravel 5.5

### ISSUE THREAD

**Issue by ddmo** [barryvdh/laravel-debugbar#779]
I've installed according to instructions but not showing on browser.

APP_DEBUG=true in my .env file
Package has been added as both a Service Provider and a Facade
I have published the config file debugbar.php for the package
Run php artisan cache:clear

Any idea?
Thanks

**Comment by tomzx** [comment]
Is this on a clean install of Laravel? It should work out of the box.

If it's not a clean install, then have you tried it on a simple page? How did you determine it isn't working?

**Comment by guizoxxv** [comment]
Check your logs at `storage/logs/larave.log`. I was getting the following with a fresh install of Laravel 5.6

> local.ERROR: Debugbar exception: mkdir(): Permission denied

If that's your case...turns out that Degubbar needs to create a folder `storage/debugbar` but wasn't able because `storage` permission is `775` by default.
My solution was to change the permission to `777` so that the folder could be created and then change it back to `775`.

> sudo chmod 777 storage/
