### ISSUE TITLE
Why error screen showing my all details ?

### ISSUE THREAD

**Issue by rahulsharma841990** [barryvdh/laravel-debugbar#793]
Is it good to seen all your env file details on error screen.

In laravel 5.5 its showing all the env variable even my database credentials, so suppose if we have to on debugger on live server to just view error description then all the visitors can see my db details.. is it good?

**Comment by matijakovacevic** [comment]
because you shouldn't use debug data on production servers in first place :)

production should be with APP_DEBUG=false
if you want to show it, use an IP address whitelist, cookie, or something...

you have programmatic fn's at your disposal, like:
LaravelDebugbar::enable();
LaravelDebugbar::disable();
