### ISSUE TITLE
Type error: Argument 1 passed to Barryvdh\Debugbar\DataCollector\GateCollector::addCheck() must be an instance of Illuminate\Contracts\Auth\Access\Authorizable

### ISSUE THREAD

**Issue by karneaud** [barryvdh/laravel-debugbar#853]
I'm implementing a Laravel policy on my blade template as follows

```
@can('edit', $model) 
........
@endcan
```

> Type error: Argument 1 passed to Barryvdh\Debugbar\DataCollector\GateCollector::addCheck() must be an instance of Illuminate\Contracts\Auth\Access\Authorizable, instance of Modules\User\Entities\Sentinel\User given, called in /../vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 374

If I disable the debug bar the error goes away

- Laravel version 5.5.40
- Laravel Debugbar - 3.1.5
- PHP version - 7.0.30

**Comment by jakubjo** [comment]
Any news on this issue?

**Comment by OrkhanAlikhanov** [comment]
I ran in a case where I was providing non-`Authenticatable` type, an organization.

```php
$this->authorizeForUser(Dashboard::current(), 'edit', $model);
```
<sup>`Dashboard::current()` returns App\Organization</sup>

Laravel is totally fine with it and forwards to correct Policy, but the GateCollector was causing crash due to `Authenticatable` parameter type requirement. #895 removes this restriction totally
