### ISSUE TITLE
\Debugbar::disable() does not disable it

### ISSUE THREAD

**Issue by rokde** [barryvdh/laravel-debugbar#872]
I have a downloadable resource stream and the DebugbarHighlightingStyleExtensionsMiddleware failed to attach to content() because a StreamedResponse has no content() method ("Call to undefined method Symfony\Component\HttpFoundation\StreamedResponse::content()") so I try to disable DebugBar with 
`\Debugbar::disable();` in my controller, but nothing happend.

Laravel 5.6.35
Laravel-Debugbar 3.1.5

Please make the disable() method workable again.

**Comment by yarcowang** [comment]
```
debugbar()->disable();
```
should work.

**Comment by catalinbuletin** [comment]
I have the same issue with Laravel 7.11 and Laravel-Debugbar 3.3.3

Neither work for me: `\Debugbar::disable();` or `debugbar()->disable();`

I have a migration script and i try to turn debugbar off for this action but it nothing is happening. 

I get `Allowed memory size exhausted` because of the QueryCollector `vendor/barryvdh/laravel-debugbar/src/DataCollector/QueryCollector.php on line 119`
