### ISSUE TITLE
Support turbolinks

### ISSUE THREAD

**Issue by garygreen** [barryvdh/laravel-debugbar#908]
It would be great if this package could improve support for [Turbolinks](https://github.com/turbolinks/turbolinks). At the moment it adds the css, scripts in the body which get executed twice causing some issues.

**Comment by barryvdh** [comment]
Related to https://github.com/barryvdh/laravel-debugbar/pull/910 ?

**Comment by garygreen** [comment]
There does seem to be a bit of a crossover with that PR. Believe turbolinks would be greatly improved if it didn't inject js/css into the body, as the core concept of turbolinks is that it replaces everything in body, but keeps everything in head only executed once - to avoid reloading js, css, etc.

**Comment by ahamilton9** [comment]
As mentioned above, Turbolinks intercepts link clicks and makes an AJAX call for the content of the requested page. It then swaps out the content of the body, which means in this case that all of the JS that Debugbar injects into the body is re-run every page click/swap. So we _do_ want Debugbar to be injected unlike in #910 , we just want Turbolinks to stop reloading the scripts tags.

I'm specifically seeing the error "jQuery is not defined" come up because `jQuery.noConflict()` has been run once initially and is then run again on page swaps but `window.jQuery` has already been cleared. The quick/dirty fix I've found is to simply wrap the no-conflict statement in JavascriptRenderer@renderHead in `if(jQuery){}` which prevents it from re-running. All the other JS runs again, but this doesn't seem to cause any other noticeable issues: the Debugbar updates and works as expected.

A proper fix might be to add a configuration option like `forTurbolinks(true)` to add the `data-turbolinks-permanent` on the script blocks so that Turbolinks does not re-run them. Alternatively we could add some way to hook into renderHead to adjust the output. Thoughts?

**Comment by garygreen** [comment]
Alternatively couldn't debugbar just inject the scripts into the `<head>`, if found? That would automatically improve turbolinks support.

As a somewhat similar issue - I personally I think it would be great if most of debugbar was lazily loaded. At the moment it renders everything, all tabs, syntax highlighting etc even if you don't click into it, which massively slows down page renders so for that reason I have it off most of the time. But guess that's a seperate issue 🤣

**Comment by ahamilton9** [comment]
I don't see any immediate reason that can't be done but it seems like more of an issue for the underlying project. The output of the code to the page is still mostly handled by PHP Debug Bar which just spits all of the necessary code out in one block. Laravel Debug Bar only overrides certain parts of the Javascript renderer. So while I agree that things like rendering the scripts to the head section or lazy loading like you mentioned would both be great, I think it would probably come to checking for/making issues in the PHP Debug Bar project rather than here: https://github.com/maximebf/php-debugbar

The fix I attached in the previous comment works within what has already been modified by the Laravel Debug Bar project. It is definitely not an ideal fix but I believe since Laravel-Livewire has been gathering some steam and they recommend Turbolinks, this is going to be more of an issue for this project.

**Comment by barryvdh** [comment]
With Telescope Toolbar I was a bit more strict for injecting it in the head. So that would just work also?
https://github.com/fruitcake/laravel-telescope-toolbar/blob/4a116e53d666c43cc35658be5b7f5ffd421b9e54/src/Toolbar.php#L117-L167

**Comment by ahamilton9** [comment]
I was unaware of the toolbar project for Telescope so I'd never really used Telescope to begin with. Just installed it to our project along with the toolbar and everything works great due to how you handled that injection. Not sure if this is a solution for the issue author, but it works for me. Thanks for the tip, and great project!

**Comment by barryvdh** [comment]
Okay will try to do that the same in Debugbar.

**Comment by barryvdh** [comment]
So does this work? https://github.com/barryvdh/laravel-debugbar/pull/1084
I tested it with Turbolinks, seems to work without the need of extra tags. It does reload the entire debugbar upon transition instead of showing it as an ajax request, but that's also how it goes without turbolinks.

**Comment by tanthammar** [comment]
Solved #1320
