### ISSUE TITLE
Only enable for 1 logged in user?

### ISSUE THREAD

**Issue by jasondavis** [barryvdh/laravel-debugbar#93]
Not an issue, but could you point me in the direction to enable this in Production for 1 logged in user, based on user ID?  I want to enable in Production for an Admin user but nobody else...I'm not sure where to best do this sort of over-ride from the app/config/app.php debug setting.  Any ideas?

**Comment by antoniopaisfernandes** [comment]
How about with Laravel 5?

**Comment by andyunleashed** [comment]
@antoniopaisfernandes I might be a bit late to the party, but I've just used a middleware for this as the old method mentioned above will no longer be appropriate.

If you fire up a new middleware (i.e `php artisan make:middleware DebugBarMiddleware`) then inside that file add the below to the handle function (the auth related lines, leave in place the return $next line: (obviously replace 1 with your chosen user id)

```
    public function handle($request, Closure $next)
    {
        if(!\Auth::check() || \Auth::user()->id !== 1) {
            \Debugbar::disable();
        }
        return $next($request);
    }
```

Then in your \App\Http\Kernel file use `\App\Http\Middleware\DebugBarMiddleware::class` inside your web middleware you can get it going. (I placed mine at the end of the web middleware list)

What the above will do is actually **disable** it if it doesn't match, rather than _enable_ - I found this works a lot nicer.

**Comment by connectkushal** [comment]
In laravel 5.5, the new middleware worked for me when, in the \App\Http\Kernel file,  i added the `DebugBarMiddleware::class` to `$routeMiddleware` instead of `web` with a key `debugbar` and then in RouteServiceProvider.php, passed it to the middleware function along with web as array, 

```
Route::middleware(['web', 'debugbar']) 
   ->namespace(....
   ->group(.....

```

without this Auth::check and Auth::user inside the DebugBarMiddleware were returning `false` and `null` for each request for some reason that am not able to figure out so far. I guess it has something to do with the changes they made to working of middleware, im not sure.

**Comment by benyanke** [comment]
Jumping in to comment that @andyunleashed 's method worked perfectly for me. I adjusted it slightly to check permissions from spatie/laravel-permission (could also use any other similar permissions engine). Also implements a config option for allowing the debug bar to be always enabled for debugging.

```
        // Ensures that users who are not logged in or
        // do not have debugbar permission will not see it
        if(
          ! config('debugbar.enable-for-all-users') &&
          (
            ! \Auth::check() ||
            ! \Auth::user()->hasPermissionTo('admin.view.debugbar')
          )
        ) {
            \Debugbar::disable();
        }
```

**Comment by alighasemzadeh** [comment]
@barryvdh 
This doesn't work for me.

**Comment by Sammaye** [comment]
Can anyone confirm this still works, I cannot get the class `\DebugBar` and I am tying to load the service provider dynamically but that also doesn't work

**Comment by MrMage** [comment]
> Can anyone confirm this still works, I cannot get the class `\DebugBar` and I am tying to load the service provider dynamically but that also doesn't work

You need to use `\Debugbar`, not `\DebugBar`.

**Comment by sngrl** [comment]
This is bad idea to enable Debugbar on each request and disable it later for some reason. For example, on "Bad CSRF-token" error Debugbar data will be shown to any user:

![image](https://user-images.githubusercontent.com/6196684/72606765-3fcf8700-3930-11ea-90e9-ae85e2031823.png)

**Comment by sngrl** [comment]
In my case I'm using @andyunleashed [method](https://github.com/barryvdh/laravel-debugbar/issues/93#issuecomment-290890589), wrote on this page, but I'm disable Debugbar on my .env file, and enable it in middleware. But on this case for some reasons Debugbar panel is not shown on the pages. So, I disabled auto-inject code in config/debugbar.php (option "inject") - because it still does not work, right? And writed some code at the bottom on Blade main layout:

```
@php
    if (Debugbar::isEnabled()) {
        $renderer = Debugbar::getJavascriptRenderer();
        echo $renderer->renderHead();
        echo $renderer->render();
    }
@endphp
```

**Comment by Sammaye** [comment]
You would disable by default and then enable if the user is admin, pages like that would slip through the net but then normally that kind of error is one you could replicate on a staging server

**Comment by hosamalzagh** [comment]
> @antoniopaisfernandes I might be a bit late to the party, but I've just used a middleware for this as the old method mentioned above will no longer be appropriate.
> 
> If you fire up a new middleware (i.e `php artisan make:middleware DebugBarMiddleware`) then inside that file add the below to the handle function (the auth related lines, leave in place the return $next line: (obviously replace 1 with your chosen user id)
> 
> ```
>     public function handle($request, Closure $next)
>     {
>         if(!\Auth::check() || \Auth::user()->id !== 1) {
>             \Debugbar::disable();
>         }
>         return $next($request);
>     }
> ```
> 
> Then in your \App\Http\Kernel file use `\App\Http\Middleware\DebugBarMiddleware::class` inside your web middleware you can get it going. (I placed mine at the end of the web middleware list)
> 
> What the above will do is actually **disable** it if it doesn't match, rather than _enable_ - I found this works a lot nicer.

not work dd( \Auth::check() , \Auth::user()    )  return false , null
